windows-msys:
	g++ code/*.cpp main.cpp -o main -Iinclude -Ilib/SFML3/include -Llib/SFML3/lib -lsfml-graphics -lsfml-window -lsfml-system -std=c++17 -w

macbrew:
	g++ code/*.cpp main.cpp -o main.out -Iinclude -I/opt/homebrew/include -L/opt/homebrew/lib -lsfml-graphics -lsfml-window -lsfml-system -std=c++17 -w

dummy: